/**
 * Cross-compatibility verification test: JS decrypts Python-issued licence.
 * Run with: npx tsx tests/compat_verify.ts
 */

import { readFileSync } from "node:fs";
import { createPrivateKey, createPublicKey } from "node:crypto";
import {
  decryptLicencePayload,
  parseLicenceOuter,
} from "../src/licence/codec";
import { verifyRsaSign } from "../src/crypto/rsa";
import { aesDecrypt, getAesKey } from "../src/crypto/aes";

// This is the licence generated by Python server
const PYTHON_LICENCE = process.argv[2];

if (!PYTHON_LICENCE) {
  console.log("Usage: npx tsx tests/compat_verify.ts <licence_string>");
  console.log("\nFirst generate a licence with Python:");
  console.log('python -c "from licence_server.licence_codec import ..."');
  process.exit(1);
}

// Convert the real private key
const privateKeyPkcs1Hex = readFileSync("keys/private.hex", "utf-8").trim();
const privateKeyPkcs1Der = Buffer.from(privateKeyPkcs1Hex, "hex");
const privKey = createPrivateKey({
  key: privateKeyPkcs1Der,
  format: "der",
  type: "pkcs1",
});
const privateKeyPkcs8Hex = (privKey.export({ format: "der", type: "pkcs8" }) as Buffer).toString("hex");

// Convert the real public key
const publicKeyPkcs1Hex = readFileSync("keys/public.hex", "utf-8").trim();
const publicKeyPkcs1Der = Buffer.from(publicKeyPkcs1Hex, "hex");
const pubKey = createPublicKey({
  key: publicKeyPkcs1Der,
  format: "der",
  type: "pkcs1",
});
const publicKeySpkiHex = (pubKey.export({ format: "der", type: "spki" }) as Buffer).toString("hex");

async function main() {
  console.log("=== Cross-Compatibility Test: JS decrypts Python licence ===\n");

  const licence = PYTHON_LICENCE.trim();
  console.log(`Licence length: ${licence.length} chars`);

  // Step 1: Parse outer structure
  console.log("\n--- Step 1: Parse outer ---");
  const [iv, ct, sig] = parseLicenceOuter(licence);
  console.log(`IV:     ${iv}`);
  console.log(`CT len: ${ct.length} hex chars`);
  console.log(`SIG:    ${sig.substring(0, 32)}... (${sig.length} hex chars)`);

  // Step 2: Verify RSA signature
  console.log("\n--- Step 2: Verify RSA signature ---");
  try {
    await verifyRsaSign(ct, sig, publicKeySpkiHex);
    console.log("✓ RSA signature VALID");
  } catch (err) {
    console.log("✗ RSA signature INVALID:", err);
    process.exit(1);
  }

  // Step 3: AES decrypt
  console.log("\n--- Step 3: AES decrypt ---");
  const inner = await aesDecrypt(getAesKey(), iv, ct);
  console.log(`Inner plaintext (${inner.length} chars):`);
  console.log(inner.substring(0, 80) + "...");

  // Step 4: Full decrypt pathway
  console.log("\n--- Step 4: Full decrypt ---");
  const [authValue, fingerprint] = await decryptLicencePayload(
    licence,
    publicKeySpkiHex
  );
  console.log("Auth info:", JSON.stringify(authValue, null, 2));
  console.log(`Fingerprint: ${fingerprint}`);

  console.log("\n✓✓✓ CROSS-COMPATIBILITY VERIFIED ✓✓✓");
  console.log("JS can successfully decrypt and verify Python-issued licences.");
}

main().catch((err) => {
  console.error("FAILED:", err);
  process.exit(1);
});
